name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/node-app:latest .
          docker push ghcr.io/${{ github.repository_owner }}/node-app:latest

      - name: Make Docker image public
        run: |
          IMAGE_URL="https://ghcr.io/v2/${{ github.repository_owner }}/node-app/tags/list"
          PACKAGE_URL="https://api.github.com/user/packages/container/node-app/visibility"
          curl -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            ${PACKAGE_URL} \
            -d '{"visibility":"public"}'

      - name: Debugging API visibility
        run: |
          echo "Checking visibility of package..."
          curl -X GET \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/node-app

